from robinhood.api_dataclasses import OptionGreekData, OptionInstrument


def build_option_instrument(
    *,
    id: str = "instrument-id",
    chain_id: str = "chain-id",
    chain_symbol: str = "SPY",
    expiration_date: str = "2026-04-17",
    strike_price: float = 500.0,
    type: str = "call",
) -> OptionInstrument:
    return OptionInstrument(
        chain_id=chain_id,
        chain_symbol=chain_symbol,
        created_at="2026-04-01T09:30:00Z",
        expiration_date=expiration_date,
        id=id,
        issue_date="2026-04-01",
        min_ticks={"cutoff_price": 3.0, "below_tick": 0.01, "above_tick": 0.05},
        rhs_tradability="tradable",
        state="active",
        strike_price=strike_price,
        tradability="tradable",
        type=type,
        updated_at="2026-04-01T09:30:00Z",
        url=f"https://api.robinhood.com/options/instruments/{id}/",
        sellout_datetime="2026-04-17T16:00:00Z",
        long_strategy_code="long_call",
        short_strategy_code="short_call",
        underlying_type="equity",
    )


def build_option_greek_data(
    *,
    instrument_id: str = "instrument-id",
    symbol: str = "SPY",
) -> OptionGreekData:
    return OptionGreekData(
        adjusted_mark_price=1.0,
        adjusted_mark_price_round_down=0.99,
        ask_price=1.05,
        ask_size=10,
        bid_price=0.95,
        bid_size=12,
        break_even_price=501.0,
        high_price=1.2,
        instrument=f"https://api.robinhood.com/options/instruments/{instrument_id}/",
        instrument_id=instrument_id,
        last_trade_price=1.0,
        last_trade_size=1,
        low_price=0.8,
        mark_price=1.0,
        open_interest=100,
        previous_close_date="2026-04-01",
        previous_close_price=0.9,
        updated_at="2026-04-01T09:30:00Z",
        volume=200,
        symbol=symbol,
        occ_symbol=f"{symbol}260417C00500000",
        state="active",
        chance_of_profit_long=0.5,
        chance_of_profit_short=0.5,
        delta=0.5,
        gamma=0.1,
        implied_volatility=0.2,
        rho=0.01,
        theta=-0.02,
        vega=0.03,
        pricing_model="black_scholes",
        high_fill_rate_buy_price=1.01,
        high_fill_rate_sell_price=0.99,
        low_fill_rate_buy_price=0.98,
        low_fill_rate_sell_price=0.96,
    )
