class RobinhoodError(Exception): ...


class OrderFailedError(RobinhoodError): ...


class InstruemtNotFoundError(RobinhoodError): ...


class AccountIdNotFoundError(RobinhoodError): ...


class MalformedOrderError(RobinhoodError): ...


class ConfigurationError(RobinhoodError): ...


class AuthenticationError(RobinhoodError): ...


class TokenExtractionError(AuthenticationError): ...
